### ISSUE TITLE
Widening CKEDITOR input box

### ISSUE THREAD

**Issue by CailinPitt** [consider-app/consider#13]
The input box is awkwardly restricted. It should be expanded to match the width of the containers holding the questions students are to respond to.

**Comment by CailinPitt** [comment]
I widened the input box so it matches the container holding the questions to respond to. I resized the submit button and put it below the input box. This looked fine to me, but if anyone would like to to change it's position/sizing I can do that.

<img width="1680" alt="screen shot 2016-11-01 at 11 57 43 am" src="https://cloud.githubusercontent.com/assets/11185489/19896364/735550b6-a02a-11e6-8e50-89d6b8ba7563.png">

**Comment by swaroopjcse** [comment]
Awesome. If not already, pl. test with different screen sizes, e.g. by widening/shortening the browser window itself.

About the position of the Submit button: how about putting it on the right of the box so that we can use one more line on the screen real estate to show the content of the post being typed in?
